export const SELECT_PICTURE = 'SELECT_PICTURE';
export const FILTER_PICTURES = 'FILTER_PICTURES';
export const REQUEST_PICTURES = 'REQUEST_PICTURES';
export const PICTURES_FETCH_ERROR = 'PICTURES_FETCH_ERROR';
export const PICTURES_FETCH_SUCCESS = 'PICTURES_FETCH_SUCCESS';